version: '3'
services:
    web:
      image: 'project1'
      ports:
        - '5000:8000'
        # host port:con_port
        
    zookeeper:
      image: 'ubuntu/zookeeper:latest'
      container_name: zookeeper
      ports:
        - '2181:2181'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes


    kafka:
      image: 'ubuntu/kafka:latest'
      container_name: kafka
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=-1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper  

    
    server:
      image: 'server:latest'
      container_name: server
      build:
        context: kafka/server
      environment:
        - PORT=8000
      depends_on:
        - kafka


    kafka-producer:
      image: 'producer:latest'
      container_name: kafka-producer
      build:
        context: kafka/producer
      environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      depends_on:
        - server


    kafka-consumer:
      image: 'consumer:latest'
      container_name: kafka-consumer
      build:
        context: kafka/consumer
      environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      depends_on:
        - kafka-producer

   
    # web:
    #   build: 
    #     context: .
    #     dockerfile: dockerfile
    #   volumes:
    #     - .:/app
    #   ports:
    #     - "8000:8000"

   
    

